"""Changes to caribbeanjobspost table

Revision ID: 4a914ff368b4
Revises: 94b517949beb
Create Date: 2022-02-01 00:46:50.315558

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4a914ff368b4'
down_revision = '94b517949beb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('caribbeanjobs_posts', 'job_listing_date',
               existing_type=sa.DATE(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('caribbeanjobs_posts', 'job_listing_date',
               existing_type=sa.DATE(),
               nullable=False)
    # ### end Alembic commands ###
