"""Initial tables

Revision ID: 897589582f92
Revises: 9985fa067616
Create Date: 2022-01-28 23:57:48.543269

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '897589582f92'
down_revision = '9985fa067616'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
