"""Changes to caribbeanjobspost table

Revision ID: 94b517949beb
Revises: a78494e99924
Create Date: 2022-02-01 00:37:05.388632

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '94b517949beb'
down_revision = 'a78494e99924'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
