"""Changes to caribbeanjobspost table

Revision ID: a78494e99924
Revises: 1147a92ad6a0
Create Date: 2022-01-29 01:15:54.626193

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a78494e99924'
down_revision = '1147a92ad6a0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('caribbeanjobs_posts', sa.Column('url', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('caribbeanjobs_posts', 'url')
    # ### end Alembic commands ###
